name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install wrangler
        run: npm install -g wrangler

      - name: Login to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}

      - name: Deploy Worker
        run: wrangler deploy
        env:
            CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
            CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }} #  THIS LINE IS ADDED
